version: "2"
checks:
  method-count:
    config:
      threshold: 30
plugins:
  duplication:
    enabled: true
  eslint:
    enabled: true
    channel: "eslint-8"
    config:
      config: config/eslintrc.json
  fixme:
    enabled: true
  markdownlint:
    enabled: true
